#########################################
# play01 - 웹서버 설정
# 1) 패키지 설치
# 2) 서비스 기동
# 3) 방화벽 등록
#########################################

- name: play01 - 웹서버 설정
  hosts: webservers
  tasks:
    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ ansible_local['custom']['general']['package']}}"
        state: present
    - name: 2) 서비스 기동
      ansible.builtin.systemd_service:
        name: "{{ ansible_local['custom']['general']['service'] }}"
        state: "{{ ansible_local['custom']['general']['state'] }}"
        enabled: true
    - name: 3) 방화벽 등록
      ansible.posix.firewalld:
        service: "{{ ansible_local['custom']['general']['fwsvc'] }}"
        state: enabled
        permanent: true
        immediate: true
