---
#############################
# 1) 방화벽 포트 제거
# 2) 웹서비스 stop
# 3) /var/www/html/index.html 파일 제거
# 4) httpd 패키지 삭제
#############################

- name: Restore site.yml
  hosts: all
  tasks: 
    - name: 1) 방화벽 포트 제거 - firewalld(http)
      ansible.posix.firewalld:
        service: http
        state: disabled
        permanent: true
        immediate: true

    - name: 2) 웹서비스 stop - systemd(httpd.service)
      ansible.builtin.systemd_service:
        name: httpd
        state: stopped
        enabled: false

    - name: 3) /var/www/html/index.html 파일 제거 - file 모듈
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) httpd 패키지 삭제
      ansible.builtin.dnf:
        name: httpd
        state: absent
